name: voter-alliance
region: nyc
static_sites:
  - name: web
    github:
      repo: NuRavenCorp/VoterAlliance-new
      branch: main
      deploy_on_push: true
    source_dir: /voter-alliance.client/dist
    catchall_document: index.html
    routes:
      - path: /

